### ISSUE TITLE
Wird kein Zielverzeichnis angegeben, wird eines angenommen, aber vorausgesetzt, dass dieses existiert

### ISSUE THREAD

**Issue by t73fde** [vlntnwbr/HanserPyLibrary#1]
Aufruf direkt nach der Installation:

`hanser-py-library https://www.hanser-elibrary.com/isbn/9783446445987`

führt zum Fehler:

    Creating '/home/stern/Documents/HanserPyLibrary'                                                    
    Traceback (most recent call last):                                                                                                                                                                      
      File "/home/USER/.local/share/virtualenvs/HanserPyLibrary-aKgPLqne/bin/hanser-py-library", line 11, in <module>                                                                                      
        load_entry_point('hanser-py-library', 'console_scripts', 'hanser-py-library')()                                                                                                                     
      File "/home/USER/work/HanserPyLibrary/hanser_py_library/main.py", line 362, in main              
        app.hanser_download(book)                                                                                                                                                                           
      File "/home/USER/work/HanserPyLibrary/hanser_py_library/main.py", line 97, in hanser_download                                                                                                        
        self.merge_and_write_pdf(pdf_list, title)
      File "/home/USER/work/HanserPyLibrary/hanser_py_library/main.py", line 116, in merge_and_write_pdf
        mkdir(self.output_dir)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/Documents/HanserPyLibrary'

Dagegen funktioniert alles, wenn Option `-fo DIR` angegeben wird.

Getestet unter Fedora 30:

    Python 3.8.0 (default, Oct 16 2019, 12:47:36) 
    [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux

**Comment by vlntnwbr** [comment]
Lang hat's gedauert, aber das Problem sollte nun behoben sein. Wird kein Zielverzeichnis angegeben, wird das Buch im aktuellen Arbeitsverzeichnis gespeichert.

Bisher getestete unter Windows 10:
```
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50)
[MSC v.1916 64 bit (AMD64)] on win32
```
